{
 "title": "Boundary Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "boundary_controller_api_http_request_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(boundary_controller_api_http_request_duration_seconds_bucket[$__rate_interval])) by (le))"
    },
    {
     "expr": "rate(boundary_controller_api_http_request_duration_seconds_count[$__rate_interval])"
    },
    {
     "expr": "rate(boundary_controller_api_http_request_duration_seconds_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "boundary_worker_proxy_websocket_active_connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boundary_worker_proxy_websocket_active_connections"
    }
   ]
  },
  {
   "title": "boundary_worker_proxy_http_write_header_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(boundary_worker_proxy_http_write_header_duration_seconds_bucket[$__rate_interval])) by (le))"
    },
    {
     "expr": "rate(boundary_worker_proxy_http_write_header_duration_seconds_count[$__rate_interval])"
    },
    {
     "expr": "rate(boundary_worker_proxy_http_write_header_duration_seconds_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "boundary_controller_api_http_request_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(boundary_controller_api_http_request_size_bytes_bucket[$__rate_interval])) by (le))"
    },
    {
     "expr": "rate(boundary_controller_api_http_request_size_bytes_count[$__rate_interval])"
    },
    {
     "expr": "rate(boundary_controller_api_http_request_size_bytes_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "boundary_worker_proxy_websocket_sent_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(boundary_worker_proxy_websocket_sent_bytes_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "boundary_controller_api_http_response_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(boundary_controller_api_http_response_size_bytes_bucket[$__rate_interval])) by (le))"
    },
    {
     "expr": "rate(boundary_controller_api_http_response_size_bytes_count[$__rate_interval])"
    },
    {
     "expr": "rate(boundary_controller_api_http_response_size_bytes_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "boundary_worker_proxy_websocket_received_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(boundary_worker_proxy_websocket_received_bytes_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "boundary_controller_cluster_grpc_request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(boundary_controller_cluster_grpc_request_duration_seconds_bucket[$__rate_interval])) by (le))"
    },
    {
     "expr": "rate(boundary_controller_cluster_grpc_request_duration_seconds_count[$__rate_interval])"
    },
    {
     "expr": "rate(boundary_controller_cluster_grpc_request_duration_seconds_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "boundary_build_info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "boundary_build_info" }
   ]
  }
 ]
}